name: Test
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 18'
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@vendpark'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PAT }}

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Lint'
        run: npm run lint

      - name: 'Test'
        run: npm run test

      - name: 'Build'
        run: npm run build
